### ISSUE TITLE
Button Disabled

### ISSUE THREAD

**Issue by DJQuadRocks** [raiguard/EditorExtensions#106]
After upgrading to 2.0.2, the shortcut button is no longer clickable. The keyboard shortcut works, but the button does not. Am I missing something?

**Comment by raiguard** [comment]
Please use the bug report template next time. Could you upload your save file so I can look?

**Comment by DJQuadRocks** [comment]
https://www.dropbox.com/s/6z32vwhjjb41c3k/Space%20Exploration%20Maxed.zip?dl=0

**Comment by raiguard** [comment]
Thanks for the save. It looks like this happens when you load a save while in the satellite view. There is no event for when the satellite view is toggled, so I don't know to update the button.

I will look into adding an event for when a player's permission group is changed. That will solve this problem.

**Comment by raiguard** [comment]
Ok, there is an event when players are added or removed, but it only fires when they're removed in the `/permissions` GUI, not when mods do it. I'll have to fix that before I can fix this issue.

**Comment by DJQuadRocks** [comment]
The latest version seems to have fixed it. Thanks!

**Comment by raiguard** [comment]
This isn't actually fixed. If you save the game while in the navsat view, then trigger a configuration change, it will happen again.

**Comment by raiguard** [comment]
The base game fix is going to come in Factorio 1.2, so I have found a temporary workaround until such time.
