### ISSUE TITLE
Can't Set Infinity Accumulator Power Over 999

### ISSUE THREAD

**Issue by adugaue** [raiguard/EditorExtensions#125]
### Description

Howdy, Flood here.

I noticed today that I couldn't set the infinity accumulator to use numbers over 999. I tried to set one to 1100 MW to emulate a 1.1GW since I couldn't use decimals but that didn't work.

Let me know if you need anything else. :]

### Reproduction

Load save file
Place an Infinity Accumulator
Try to set power to 1100 MW.

**Comment by raiguard** [comment]
After looking into this, I've decided this isn't worth adding. It's not able to easily remember which unit you're on because it updates the GUI by getting the current settings from the entity, so I'd have to add a tag, which means adding it to blueprints et al. Just not worth it.

I fixed the decimals, so you can put 1.1 GW now.
