### ISSUE TITLE
Companion Drones attack in MP

### ISSUE THREAD

**Issue by Yokmp** [raiguard/EditorExtensions#135]
### Description

As soon as is switch surfaces our drones attack each other. Also it seems like 2 players can't be on the same Editor-Surface. There are also some permission issues. Like host can easily switch between surfaces but others can't.
Game is hostet locally and connected via Steam.

**Comment by raiguard** [comment]
The first issue is because you change to a different force when you go into the lab. The second half isn't an issue, a player needs to be an administrator in order to use the map editor.

In a MP game I recommend using blueprint sandboxes instead of EE unless you fully trust the other players and feel comfortable giving them admin rights.
