### ISSUE TITLE
Feature Reqeust: Add second Input for Infinity loader

### ISSUE THREAD

**Issue by malte9799** [raiguard/EditorExtensions#147]
Please add a second input slot for the Infinity loader. So it can output different items for each lane.

**Comment by raiguard** [comment]
This feature used to exist but was removed in 2.0 due to some unfixable issues. I am investigating adding per-lane loader filter support on the game engine side, and if that ends up happening, the infinity loader will gain that capability back. But unless that happens, it will remain a single filter.

**Comment by raiguard** [comment]
The requisite support was added to the Factorio engine, so this can finally happen!
