### ISSUE TITLE
Additional Lamps & Walls

### ISSUE THREAD

**Issue by 1993Pianist** [raiguard/EditorExtensions#98]
### Description

Hi Raiguard
I love this mod. It's great for experimenting and creating new blueprints. Please add colored lamps and walls if possible. Thank you

**Comment by raiguard** [comment]
Thanks for the suggestion. How would colored walls and lamps assist you with testing? It doesn't seem very in-scope for editor extensions.

**Comment by 1993Pianist** [comment]
I use colored lamps to make creative designs with the help of circuit networks. Colored walls also add variety, which I like :)

**Comment by 1993Pianist** [comment]
There is a color-coded mod for this purpose, but I personally prefer using editor extensions in all respects.

**Comment by raiguard** [comment]
I don't really feel that this is in scope for Editor Extensions, especially since there is another mod that already does this. I appreciate the suggestion though!

A note for the future: there is an "open a blank issue" button below the template that you can use for feature requests. It's pretty hard to see. I am looking into ways to make that better.

**Comment by 1993Pianist** [comment]
OK, no problem at all. For me, the editor extensions is one of the best mods for Factorio. Thank you so much for creating it. Good luck.

**Comment by raiguard** [comment]
Thanks for the compliment! I'm glad that you enjoy the mod.
